name: Pipelines

on:
  push:
    branches: ['*']

jobs:
  pipelines:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.11.4
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: 'laravel-k8s_test'
          MYSQL_ROOT_PASSWORD: 'root_in'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Prepare app
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: List contents
      run: ls -la

    - name: Test contents
      run: cat .env && cat .env.ci

    - name: Symlink storage
      run: php artisan storage:link

    - name: Refresh database
      run: php artisan migrate:fresh
      env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel-k8s_test
          DB_USERNAME: root
          DB_PASSWORD: root_in

    - name: Unit test
      run: php artisan test --testsuite=Unit
      env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel-k8s_test
          DB_USERNAME: root
          DB_PASSWORD: root_in

    - name: Feature test
      run: php artisan test --testsuite=Feature
      env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel-k8s_test
          DB_USERNAME: root
          DB_PASSWORD: root_in


